version: '3'
services:
  gsecrets:
    build: .
    entrypoint: gsecrets
    volumes:
      - .:/app
      - $HOME/.config/gcloud:/root/.config/gcloud  # credentials for google provider
    environment:
      - GOOGLE_PROJECT=oee-dev-145623
      - GCS_BUCKET=oee-test-secrets
  gsecrets_test:
    build: .
    entrypoint: tox
    volumes:
      - .:/app
      - $HOME/.config/gcloud:/root/.config/gcloud  # credentials for google provider
    environment:
      - GOOGLE_PROJECT=oee-dev-145623
      - GCS_BUCKET=oee-test-secrets