version: '3'
services:
  shell:
    build: .
    image: gsecrets
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app
      - /app/tests/__pycache__/
  gsecrets:
    image: gsecrets
    entrypoint: gsecrets
    volumes:
      - .:/app
      - $HOME/.config/gcloud:/root/.config/gcloud  # credentials for google provider
    environment:
      - GOOGLE_PROJECT=oee-dev-145623
      - GCS_BUCKET=oee-test-secrets
  gsecrets_test:
    image: gsecrets
    entrypoint: tox
    volumes:
      - .:/app
      - $HOME/.config/gcloud:/root/.config/gcloud  # credentials for google provider
    environment:
      - GOOGLE_PROJECT=oee-dev-145623
      - GCS_BUCKET=oee-test-secrets
